#include "LED.h"

#include "rodos.h"


GPIO_PIN GREEN  = GPIO_060;
GPIO_PIN ORANGE = GPIO_061;
GPIO_PIN RED    = GPIO_062;
GPIO_PIN BLUE   = GPIO_063;

HAL_GPIO greenLED = HAL_GPIO(GREEN);
HAL_GPIO orangeLED = HAL_GPIO(ORANGE);
HAL_GPIO redLED = HAL_GPIO(RED);
HAL_GPIO blueLED = HAL_GPIO(BLUE);
